name: kurztrip_ma
description: A delivery route optimization app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^6.1.1
  graphql: ^4.0.1
  data_connection_checker: ^0.3.4
  flutter_bloc: ^7.0.0
  dartz: ^0.9.2
  equatable: ^2.0.0
  formz: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Kameron
      fonts:
        - asset: assets/fonts/Kameron-Regular.ttf
        - asset: assets/fonts/Kameron-Bold.ttf
          weight: 700
    - family: Teko
      fonts:
        - asset: assets/fonts/Teko-SemiBold.ttf
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
    - family:  KurztripIcons
      fonts:
       - asset: assets/icons/KurztripIcons.ttf
  assets:
    - assets/
  uses-material-design: true
