name: kurztrip_ma
description: A delivery route optimization app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dartz: ^0.10.0
  data_connection_checker: ^0.3.4
  equatable: ^2.0.3
  firebase_core: ^1.5.0
  firebase_messaging: ^10.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_google_places: ^0.3.0
  formz: ^0.4.0
  get_it: ^7.2.0
  google_maps_flutter: ^2.0.6
  google_maps_webservice: ^0.0.20-nullsafety.5
  graphql: ^5.0.0
  json_annotation: ^4.0.1
  shared_preferences: ^2.0.6

dev_dependencies:
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.4

flutter:
  fonts:
    - family: Kameron
      fonts:
        - asset: assets/fonts/Kameron-Regular.ttf
        - asset: assets/fonts/Kameron-Bold.ttf
          weight: 700
    - family: Teko
      fonts:
        - asset: assets/fonts/Teko-SemiBold.ttf
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
    - family: KurztripIcons
      fonts:
        - asset: assets/icons/KurztripIcons.ttf
  assets:
    - assets/
  uses-material-design: true
